apiVersion: alloydbomni.dbadmin.goog/v1
kind: DBInstance
metadata:
  name: foo-rp-1
spec:
  instanceType: ReadPool
  dbcParent:
    name: foo
  schedulingconfig:
    tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    nodeaffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: another-node-label-key
            operator: In
            values:
            - another-node-label-value
